name: Generate Version.swift from Git Tag

on:
  push:
    tags:
      - '*'  # Se activa con cualquier tag

jobs:
  update-version-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para acceder a tags y ramas

      - name: Fetch and checkout main
        run: |
          git fetch origin main
          git checkout main

      - name: Extract tag name
        id: get_tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate Version.swift
        run: |
          mkdir -p Sources/AlertComponent
          echo "public let GitTagVersion = \"${{ steps.get_tag.outputs.tag_name }}\"" > Sources/AlertComponent/Version.swift

      - name: Commit and push Version.swift
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add Sources/AlertComponent/Version.swift

          # Solo hacer commit si hay cambios
          if ! git diff --cached --quiet; then
            git commit -m "chore: update Version.swift for tag ${{ steps.get_tag.outputs.tag_name }}"
            git push origin main
          else
            echo "No changes to commit"
          fi
